travis:
  secure:
    BINSTAR_TOKEN: HytwoY3s9gjZLw8hkGeZLlRlYVghyeRleyPk8ssZTHrTtFTRnRLrhH6SJ6O1nw6HVoEWXl+0HU0k0GJbki5HGw7epJhqWBm7Z5xh7w9CqSxdrW+LjVkgDo+3oJpGupICrivh+Bz5WGDGmSOT9yEWLWE3OpteMUuYKN9d1oSiAjJYNGdTopI0yWa8+0Y0Kd6i/3sEuZUVdyTgP7TxjXsBbxU9qrBZtxSGS1TyBX+D8w8myhZn0/s7ikW87zhxVneZeptI3G+I6di00xANhSBCiNEHEuTtxbAPEGrfozdi8bEoFRki5qkQQcr2tI/SBLVLGjXg/JGDZi1kIw1FcAQPfc2CLHcJzz7IS7fSJTI6gX4NoZ1M3BDh3NiKxWTA6yVY87cSIlmusNmqtzO5/hXbZfDPYqbi7FOuQASnnT2gfYymJ3hw44VCeNzJYMQD8LQYGRNazgUo49XvUAacIm3nOt1ztz/5u7dzvoJIl9n+fk5HEGVRpK0939zs3ounxUVjWeyeOjXz64IYHJ5j+F2FWOpV/vwOYMIreVhMQ+CBQJI0nLOB1Q5FkS35E3NrvArsOVrijgkeNVuvK3ymwd1pAOQCaUsfGKxXsgieeKKdyusWJonnWFecr1C3GKrfLQW243Hbe7y8GZevIjX9p0o/89+MrmZ7HxzFc8/BcjpQV40=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
